export const countries: any = {
  AF: { name: "Afghanistan", code: "AF", isziprequired: "T" },
  AX: { name: "Aland Islands", code: "AX", isziprequired: "T" },
  AL: { name: "Albania", code: "AL", isziprequired: "T" },
  DZ: { name: "Algeria", code: "DZ", isziprequired: "T" },
  AS: { name: "American Samoa", code: "AS", isziprequired: "T" },
  AD: { name: "Andorra", code: "AD", isziprequired: "T" },
  AO: { name: "Angola", code: "AO", isziprequired: "T" },
  AI: { name: "Anguilla", code: "AI", isziprequired: "T" },
  AQ: { name: "Antarctica", code: "AQ", isziprequired: "T" },
  AG: { name: "Antigua and Barbuda", code: "AG", isziprequired: "T" },
  AR: { name: "Argentina", code: "AR", isziprequired: "T" },
  AM: { name: "Armenia", code: "AM", isziprequired: "T" },
  AW: { name: "Aruba", code: "AW", isziprequired: "T" },
  AU: {
    name: "Australia",
    code: "AU",
    isziprequired: "T",
    states: [
      { name: "Australian Capital Territory", code: "ACT" },
      { name: "New South Wales", code: "NSW" },
      { name: "Northern Territory", code: "NT" },
      { name: "Queensland", code: "QLD" },
      { name: "South Australia", code: "SA" },
      { name: "Tasmania", code: "TAS" },
      { name: "Victoria", code: "VIC" },
      { name: "Western Australia", code: "WA" },
    ],
  },
  AT: { name: "Austria", code: "AT", isziprequired: "T" },
  AZ: { name: "Azerbaijan", code: "AZ", isziprequired: "T" },
  BS: { name: "Bahamas", code: "BS", isziprequired: "F" },
  BH: { name: "Bahrain", code: "BH", isziprequired: "T" },
  BD: { name: "Bangladesh", code: "BD", isziprequired: "T" },
  BB: { name: "Barbados", code: "BB", isziprequired: "T" },
  BY: { name: "Belarus", code: "BY", isziprequired: "T" },
  BE: { name: "Belgium", code: "BE", isziprequired: "T" },
  BZ: { name: "Belize", code: "BZ", isziprequired: "T" },
  BJ: { name: "Benin", code: "BJ", isziprequired: "T" },
  BM: { name: "Bermuda", code: "BM", isziprequired: "T" },
  BT: { name: "Bhutan", code: "BT", isziprequired: "T" },
  BO: { name: "Bolivia", code: "BO", isziprequired: "F" },
  BQ: {
    name: "Bonaire, Saint Eustatius and Saba",
    code: "BQ",
    isziprequired: "T",
  },
  BA: { name: "Bosnia and Herzegovina", code: "BA", isziprequired: "T" },
  BW: { name: "Botswana", code: "BW", isziprequired: "T" },
  BV: { name: "Bouvet Island", code: "BV", isziprequired: "T" },
  BR: { name: "Brazil", code: "BR", isziprequired: "T" },
  IO: {
    name: "British Indian Ocean Territory",
    code: "IO",
    isziprequired: "T",
  },
  BN: { name: "Brunei Darussalam", code: "BN", isziprequired: "T" },
  BG: { name: "Bulgaria", code: "BG", isziprequired: "T" },
  BF: { name: "Burkina Faso", code: "BF", isziprequired: "T" },
  BI: { name: "Burundi", code: "BI", isziprequired: "T" },
  KH: { name: "Cambodia", code: "KH", isziprequired: "T" },
  CM: { name: "Cameroon", code: "CM", isziprequired: "T" },
  CA: {
    name: "Canada",
    code: "CA",
    isziprequired: "T",
    states: [
      { name: "Alberta", code: "AB" },
      { name: "British Columbia", code: "BC" },
      { name: "Manitoba", code: "MB" },
      { name: "New Brunswick", code: "NB" },
      { name: "Newfoundland", code: "NL" },
      { name: "Northwest Territories", code: "NT" },
      { name: "Nova Scotia", code: "NS" },
      { name: "Nunavut", code: "NU" },
      { name: "Ontario", code: "ON" },
      { name: "Prince Edward Island", code: "PE" },
      { name: "Quebec", code: "QC" },
      { name: "Saskatchewan", code: "SK" },
      { name: "Yukon", code: "YT" },
    ],
  },
  IC: { name: "Canary Islands", code: "IC", isziprequired: "T" },
  CV: { name: "Cape Verde", code: "CV", isziprequired: "T" },
  KY: { name: "Cayman Islands", code: "KY", isziprequired: "T" },
  CF: { name: "Central African Republic", code: "CF", isziprequired: "T" },
  EA: { name: "Ceuta and Melilla", code: "EA", isziprequired: "T" },
  TD: { name: "Chad", code: "TD", isziprequired: "T" },
  CL: { name: "Chile", code: "CL", isziprequired: "F" },
  CN: {
    name: "China",
    code: "CN",
    isziprequired: "T",
    states: [
      { name: "Heilongjiang Province", code: "黑龙江省" },
      { name: "Jilin Province", code: "吉林省" },
      { name: "Liaoning Province", code: "辽宁省" },
      { name: "Neimenggu A. R.", code: "内蒙古" },
      { name: "Gansu Province", code: "甘肃省" },
      { name: "Ningxia A. R.", code: "宁夏回族自治区" },
      { name: "Xinjiang A. R.", code: "新疆维吾尔族自治区" },
      { name: "Qinghai Province", code: "青海省" },
      { name: "Hebei Province", code: "河北省" },
      { name: "Henan Province", code: "河南省" },
      { name: "Shandong Province", code: "山东省" },
      { name: "Shanxi Province", code: "山西省" },
      { name: "Shaanxi Province", code: "陕西省" },
      { name: "Jiangsu Province", code: "江苏省" },
      { name: "Zhejiang Province", code: "浙江省" },
      { name: "Anhui Province", code: "安徽省" },
      { name: "Hubei Province", code: "湖北省" },
      { name: "Hunan Province", code: "湖南省" },
      { name: "Sichuan Province", code: "四川省" },
      { name: "Guizhou Province", code: "贵州省" },
      { name: "Jiangxi Province", code: "江西省" },
      { name: "Guangdong Province", code: "广东省" },
      { name: "Guangxi A. R.", code: "广西壮族自治区" },
      { name: "Yunnan Province", code: "云南省" },
      { name: "Hainan Province", code: "海南省" },
      { name: "Xizang A. R.", code: "西藏藏族自治区" },
      { name: "Beijing", code: "北京市" },
      { name: "Shanghai", code: "上海市" },
      { name: "Tianjin", code: "天津市" },
      { name: "Chongqing", code: "重庆市" },
      { name: "Fujian Province", code: "福建省" },
    ],
  },
  CX: { name: "Christmas Island", code: "CX", isziprequired: "T" },
  CC: { name: "Cocos (Keeling) Islands", code: "CC", isziprequired: "T" },
  CO: { name: "Colombia", code: "CO", isziprequired: "F" },
  KM: { name: "Comoros", code: "KM", isziprequired: "T" },
  CD: {
    name: "Congo, Democratic Republic of",
    code: "CD",
    isziprequired: "T",
  },
  CG: { name: "Congo, Republic of", code: "CG", isziprequired: "T" },
  CK: { name: "Cook Islands", code: "CK", isziprequired: "T" },
  CR: { name: "Costa Rica", code: "CR", isziprequired: "T" },
  CI: { name: "Cote d'Ivoire", code: "CI", isziprequired: "T" },
  HR: { name: "Croatia/Hrvatska", code: "HR", isziprequired: "T" },
  CU: { name: "Cuba", code: "CU", isziprequired: "T" },
  CW: { name: "Curaçao", code: "CW", isziprequired: "T" },
  CY: { name: "Cyprus", code: "CY", isziprequired: "T" },
  CZ: { name: "Czech Republic", code: "CZ", isziprequired: "T" },
  DK: { name: "Denmark", code: "DK", isziprequired: "T" },
  DJ: { name: "Djibouti", code: "DJ", isziprequired: "T" },
  DM: { name: "Dominica", code: "DM", isziprequired: "T" },
  DO: { name: "Dominican Republic", code: "DO", isziprequired: "T" },
  TL: { name: "East Timor", code: "TL", isziprequired: "T" },
  EC: { name: "Ecuador", code: "EC", isziprequired: "T" },
  EG: { name: "Egypt", code: "EG", isziprequired: "T" },
  SV: { name: "El Salvador", code: "SV", isziprequired: "T" },
  GQ: { name: "Equatorial Guinea", code: "GQ", isziprequired: "T" },
  ER: { name: "Eritrea", code: "ER", isziprequired: "T" },
  EE: { name: "Estonia", code: "EE", isziprequired: "T" },
  ET: { name: "Ethiopia", code: "ET", isziprequired: "T" },
  FK: { name: "Falkland Islands", code: "FK", isziprequired: "T" },
  FO: { name: "Faroe Islands", code: "FO", isziprequired: "T" },
  FJ: { name: "Fiji", code: "FJ", isziprequired: "T" },
  FI: { name: "Finland", code: "FI", isziprequired: "T" },
  FR: { name: "France", code: "FR", isziprequired: "T" },
  GF: { name: "French Guiana", code: "GF", isziprequired: "T" },
  PF: { name: "French Polynesia", code: "PF", isziprequired: "T" },
  TF: { name: "French Southern Territories", code: "TF", isziprequired: "T" },
  GA: { name: "Gabon", code: "GA", isziprequired: "T" },
  GM: { name: "Gambia", code: "GM", isziprequired: "T" },
  GE: { name: "Georgia", code: "GE", isziprequired: "T" },
  DE: { name: "Germany", code: "DE", isziprequired: "T" },
  GH: { name: "Ghana", code: "GH", isziprequired: "T" },
  GI: { name: "Gibraltar", code: "GI", isziprequired: "T" },
  GR: { name: "Greece", code: "GR", isziprequired: "T" },
  GL: { name: "Greenland", code: "GL", isziprequired: "T" },
  GD: { name: "Grenada", code: "GD", isziprequired: "T" },
  GP: { name: "Guadeloupe", code: "GP", isziprequired: "T" },
  GU: { name: "Guam", code: "GU", isziprequired: "T" },
  GT: { name: "Guatemala", code: "GT", isziprequired: "T" },
  GG: { name: "Guernsey", code: "GG", isziprequired: "T" },
  GN: { name: "Guinea", code: "GN", isziprequired: "T" },
  GW: { name: "Guinea-Bissau", code: "GW", isziprequired: "T" },
  GY: { name: "Guyana", code: "GY", isziprequired: "T" },
  HT: { name: "Haiti", code: "HT", isziprequired: "T" },
  HM: { name: "Heard and McDonald Islands", code: "HM", isziprequired: "T" },
  VA: {
    name: "Holy See (City Vatican State)",
    code: "VA",
    isziprequired: "T",
  },
  HN: { name: "Honduras", code: "HN", isziprequired: "T" },
  HK: { name: "Hong Kong", code: "HK", isziprequired: "F" },
  HU: { name: "Hungary", code: "HU", isziprequired: "T" },
  IS: { name: "Iceland", code: "IS", isziprequired: "T" },
  IN: { name: "India", code: "IN", isziprequired: "T" },
  ID: { name: "Indonesia", code: "ID", isziprequired: "T" },
  IR: { name: "Iran (Islamic Republic of)", code: "IR", isziprequired: "T" },
  IQ: { name: "Iraq", code: "IQ", isziprequired: "T" },
  IE: { name: "Ireland", code: "IE", isziprequired: "F" },
  IM: { name: "Isle of Man", code: "IM", isziprequired: "T" },
  IL: { name: "Israel", code: "IL", isziprequired: "T" },
  IT: { name: "Italy", code: "IT", isziprequired: "T" },
  JM: { name: "Jamaica", code: "JM", isziprequired: "T" },
  JP: {
    name: "Japan",
    code: "JP",
    isziprequired: "T",
    states: [
      { name: "Hokkaidō", code: "北海道" },
      { name: "Aomori", code: "青森県" },
      { name: "Iwate", code: "岩手県" },
      { name: "Miyagi", code: "宮城県" },
      { name: "Akita", code: "秋田県" },
      { name: "Yamagata", code: "山形県" },
      { name: "Fukushima", code: "福島県" },
      { name: "Ibaraki", code: "茨城県" },
      { name: "Tochigi", code: "栃木県" },
      { name: "Gunma", code: "群馬県" },
      { name: "Saitama", code: "埼玉県" },
      { name: "Chiba", code: "千葉県" },
      { name: "Tokyo", code: "東京都" },
      { name: "Kanagawa", code: "神奈川県" },
      { name: "Niigata", code: "新潟県" },
      { name: "Toyama", code: "富山県" },
      { name: "Ishikawa", code: "石川県" },
      { name: "Fukui", code: "福井県" },
      { name: "Yamanashi", code: "山梨県" },
      { name: "Nagano", code: "長野県" },
      { name: "Gifu", code: "岐阜県" },
      { name: "Shizuoka", code: "静岡県" },
      { name: "Aichi", code: "愛知県" },
      { name: "Mie", code: "三重県" },
      { name: "Shiga", code: "滋賀県" },
      { name: "Kyoto", code: "京都府" },
      { name: "Osaka", code: "大阪府" },
      { name: "Hyōgo", code: "兵庫県" },
      { name: "Nara", code: "奈良県" },
      { name: "Wakayama", code: "和歌山県" },
      { name: "Tottori", code: "鳥取県" },
      { name: "Shimane", code: "島根県" },
      { name: "Okayama", code: "岡山県" },
      { name: "Hiroshima", code: "広島県" },
      { name: "Yamaguchi", code: "山口県" },
      { name: "Tokushima", code: "徳島県" },
      { name: "Kagawa", code: "香川県" },
      { name: "Ehime", code: "愛媛県" },
      { name: "Kochi", code: "高知県" },
      { name: "Fukuoka", code: "福岡県" },
      { name: "Saga", code: "佐賀県" },
      { name: "Nagasaki", code: "長崎県" },
      { name: "Kumamoto", code: "熊本県" },
      { name: "Ōita", code: "大分県" },
      { name: "Miyazaki", code: "宮崎県" },
      { name: "Kagoshima", code: "鹿児島県" },
      { name: "Okinawa", code: "沖縄県" },
    ],
  },
  JE: { name: "Jersey", code: "JE", isziprequired: "T" },
  JO: { name: "Jordan", code: "JO", isziprequired: "T" },
  KZ: { name: "Kazakhstan", code: "KZ", isziprequired: "T" },
  KE: { name: "Kenya", code: "KE", isziprequired: "T" },
  KI: { name: "Kiribati", code: "KI", isziprequired: "T" },
  KP: {
    name: "Korea, Democratic People's Republic",
    code: "KP",
    isziprequired: "T",
  },
  KR: { name: "Korea, Republic of", code: "KR", isziprequired: "T" },
  XK: { name: "Kosovo", code: "XK", isziprequired: "T" },
  KW: { name: "Kuwait", code: "KW", isziprequired: "T" },
  KG: { name: "Kyrgyzstan", code: "KG", isziprequired: "T" },
  LA: {
    name: "Lao People's Democratic Republic",
    code: "LA",
    isziprequired: "T",
  },
  LV: { name: "Latvia", code: "LV", isziprequired: "T" },
  LB: { name: "Lebanon", code: "LB", isziprequired: "T" },
  LS: { name: "Lesotho", code: "LS", isziprequired: "T" },
  LR: { name: "Liberia", code: "LR", isziprequired: "T" },
  LY: { name: "Libya", code: "LY", isziprequired: "T" },
  LI: { name: "Liechtenstein", code: "LI", isziprequired: "T" },
  LT: { name: "Lithuania", code: "LT", isziprequired: "T" },
  LU: { name: "Luxembourg", code: "LU", isziprequired: "T" },
  MO: { name: "Macau", code: "MO", isziprequired: "F" },
  MK: { name: "Macedonia", code: "MK", isziprequired: "T" },
  MG: { name: "Madagascar", code: "MG", isziprequired: "T" },
  MW: { name: "Malawi", code: "MW", isziprequired: "T" },
  MY: { name: "Malaysia", code: "MY", isziprequired: "T" },
  MV: { name: "Maldives", code: "MV", isziprequired: "T" },
  ML: { name: "Mali", code: "ML", isziprequired: "T" },
  MT: { name: "Malta", code: "MT", isziprequired: "T" },
  MH: { name: "Marshall Islands", code: "MH", isziprequired: "T" },
  MQ: { name: "Martinique", code: "MQ", isziprequired: "T" },
  MR: { name: "Mauritania", code: "MR", isziprequired: "T" },
  MU: { name: "Mauritius", code: "MU", isziprequired: "F" },
  YT: { name: "Mayotte", code: "YT", isziprequired: "T" },
  MX: {
    name: "Mexico",
    code: "MX",
    isziprequired: "T",
    states: [
      { name: "Aguascalientes", code: "AGS" },
      { name: "Baja California", code: "BC" },
      { name: "Baja California Norte (obsolete)", code: "BCN" },
      { name: "Baja California Sur", code: "BCS" },
      { name: "Campeche", code: "CAM" },
      { name: "Chiapas", code: "CHIS" },
      { name: "Chihuahua", code: "CHIH" },
      { name: "Coahuila", code: "COAH" },
      { name: "Colima", code: "COL" },
      { name: "Distrito Federal (obsolete)", code: "DF" },
      { name: "Durango", code: "DGO" },
      { name: "Guanajuato", code: "GTO" },
      { name: "Guerrero", code: "GRO" },
      { name: "Hidalgo", code: "HGO" },
      { name: "Jalisco", code: "JAL" },
      { name: "Mexico City", code: "CDMX" },
      { name: "Michoacán", code: "MICH" },
      { name: "Morelos", code: "MOR" },
      { name: "México (Estado de)", code: "MEX" },
      { name: "Nayarit", code: "NAY" },
      { name: "Nuevo León", code: "NL" },
      { name: "Oaxaca", code: "OAX" },
      { name: "Puebla", code: "PUE" },
      { name: "Querétaro", code: "QRO" },
      { name: "Quintana Roo", code: "QROO" },
      { name: "San Luis Potosí", code: "SLP" },
      { name: "Sinaloa", code: "SIN" },
      { name: "Sonora", code: "SON" },
      { name: "Tabasco", code: "TAB" },
      { name: "Tamaulipas", code: "TAMPS" },
      { name: "Tlaxcala", code: "TLAX" },
      { name: "Veracruz", code: "VER" },
      { name: "Yucatán", code: "YUC" },
      { name: "Zacatecas", code: "ZAC" },
    ],
  },
  FM: {
    name: "Micronesia, Federal State of",
    code: "FM",
    isziprequired: "T",
  },
  MD: { name: "Moldova, Republic of", code: "MD", isziprequired: "T" },
  MC: { name: "Monaco", code: "MC", isziprequired: "T" },
  MN: { name: "Mongolia", code: "MN", isziprequired: "T" },
  ME: { name: "Montenegro", code: "ME", isziprequired: "T" },
  MS: { name: "Montserrat", code: "MS", isziprequired: "T" },
  MA: { name: "Morocco", code: "MA", isziprequired: "T" },
  MZ: { name: "Mozambique", code: "MZ", isziprequired: "T" },
  MM: { name: "Myanmar (Burma)", code: "MM", isziprequired: "T" },
  NA: { name: "Namibia", code: "NA", isziprequired: "T" },
  NR: { name: "Nauru", code: "NR", isziprequired: "T" },
  NP: { name: "Nepal", code: "NP", isziprequired: "T" },
  NL: { name: "Netherlands", code: "NL", isziprequired: "T" },
  AN: {
    name: "Netherlands Antilles (Deprecated)",
    code: "AN",
    isziprequired: "T",
  },
  NC: { name: "New Caledonia", code: "NC", isziprequired: "T" },
  NZ: { name: "New Zealand", code: "NZ", isziprequired: "T" },
  NI: { name: "Nicaragua", code: "NI", isziprequired: "T" },
  NE: { name: "Niger", code: "NE", isziprequired: "T" },
  NG: { name: "Nigeria", code: "NG", isziprequired: "T" },
  NU: { name: "Niue", code: "NU", isziprequired: "T" },
  NF: { name: "Norfolk Island", code: "NF", isziprequired: "T" },
  MP: { name: "Northern Mariana Islands", code: "MP", isziprequired: "T" },
  NO: { name: "Norway", code: "NO", isziprequired: "T" },
  OM: { name: "Oman", code: "OM", isziprequired: "T" },
  PK: { name: "Pakistan", code: "PK", isziprequired: "T" },
  PW: { name: "Palau", code: "PW", isziprequired: "T" },
  PA: { name: "Panama", code: "PA", isziprequired: "T" },
  PG: { name: "Papua New Guinea", code: "PG", isziprequired: "T" },
  PY: { name: "Paraguay", code: "PY", isziprequired: "T" },
  PE: { name: "Peru", code: "PE", isziprequired: "T" },
  PH: { name: "Philippines", code: "PH", isziprequired: "T" },
  PN: { name: "Pitcairn Island", code: "PN", isziprequired: "T" },
  PL: { name: "Poland", code: "PL", isziprequired: "T" },
  PT: { name: "Portugal", code: "PT", isziprequired: "T" },
  PR: { name: "Puerto Rico", code: "PR", isziprequired: "T" },
  QA: { name: "Qatar", code: "QA", isziprequired: "T" },
  RE: { name: "Reunion Island", code: "RE", isziprequired: "T" },
  RO: { name: "Romania", code: "RO", isziprequired: "T" },
  RU: { name: "Russian Federation", code: "RU", isziprequired: "T" },
  RW: { name: "Rwanda", code: "RW", isziprequired: "T" },
  BL: { name: "Saint Barthélemy", code: "BL", isziprequired: "T" },
  SH: { name: "Saint Helena", code: "SH", isziprequired: "T" },
  KN: { name: "Saint Kitts and Nevis", code: "KN", isziprequired: "T" },
  LC: { name: "Saint Lucia", code: "LC", isziprequired: "T" },
  MF: { name: "Saint Martin", code: "MF", isziprequired: "T" },
  VC: {
    name: "Saint Vincent and the Grenadines",
    code: "VC",
    isziprequired: "T",
  },
  WS: { name: "Samoa", code: "WS", isziprequired: "T" },
  SM: { name: "San Marino", code: "SM", isziprequired: "T" },
  ST: { name: "Sao Tome and Principe", code: "ST", isziprequired: "T" },
  SA: { name: "Saudi Arabia", code: "SA", isziprequired: "T" },
  SN: { name: "Senegal", code: "SN", isziprequired: "T" },
  RS: { name: "Serbia", code: "RS", isziprequired: "T" },
  CS: {
    name: "Serbia and Montenegro (Deprecated)",
    code: "CS",
    isziprequired: "T",
  },
  SC: { name: "Seychelles", code: "SC", isziprequired: "T" },
  SL: { name: "Sierra Leone", code: "SL", isziprequired: "T" },
  SG: { name: "Singapore", code: "SG", isziprequired: "F" },
  SX: { name: "Sint Maarten", code: "SX", isziprequired: "T" },
  SK: { name: "Slovak Republic", code: "SK", isziprequired: "T" },
  SI: { name: "Slovenia", code: "SI", isziprequired: "T" },
  SB: { name: "Solomon Islands", code: "SB", isziprequired: "T" },
  SO: { name: "Somalia", code: "SO", isziprequired: "T" },
  ZA: { name: "South Africa", code: "ZA", isziprequired: "T" },
  GS: { name: "South Georgia", code: "GS", isziprequired: "T" },
  SS: { name: "South Sudan", code: "SS", isziprequired: "T" },
  ES: { name: "Spain", code: "ES", isziprequired: "T" },
  LK: { name: "Sri Lanka", code: "LK", isziprequired: "T" },
  PM: { name: "St. Pierre and Miquelon", code: "PM", isziprequired: "T" },
  PS: { name: "State of Palestine", code: "PS", isziprequired: "T" },
  SD: { name: "Sudan", code: "SD", isziprequired: "T" },
  SR: { name: "Suriname", code: "SR", isziprequired: "T" },
  SJ: {
    name: "Svalbard and Jan Mayen Islands",
    code: "SJ",
    isziprequired: "T",
  },
  SZ: { name: "Swaziland", code: "SZ", isziprequired: "T" },
  SE: { name: "Sweden", code: "SE", isziprequired: "T" },
  CH: { name: "Switzerland", code: "CH", isziprequired: "T" },
  SY: { name: "Syrian Arab Republic", code: "SY", isziprequired: "T" },
  TW: { name: "Taiwan", code: "TW", isziprequired: "T" },
  TJ: { name: "Tajikistan", code: "TJ", isziprequired: "T" },
  TZ: { name: "Tanzania", code: "TZ", isziprequired: "T" },
  TH: { name: "Thailand", code: "TH", isziprequired: "T" },
  TG: { name: "Togo", code: "TG", isziprequired: "T" },
  TK: { name: "Tokelau", code: "TK", isziprequired: "T" },
  TO: { name: "Tonga", code: "TO", isziprequired: "T" },
  TT: { name: "Trinidad and Tobago", code: "TT", isziprequired: "T" },
  TN: { name: "Tunisia", code: "TN", isziprequired: "T" },
  TR: { name: "Turkey", code: "TR", isziprequired: "T" },
  TM: { name: "Turkmenistan", code: "TM", isziprequired: "T" },
  TC: { name: "Turks and Caicos Islands", code: "TC", isziprequired: "T" },
  TV: { name: "Tuvalu", code: "TV", isziprequired: "T" },
  UM: { name: "US Minor Outlying Islands", code: "UM", isziprequired: "T" },
  UG: { name: "Uganda", code: "UG", isziprequired: "T" },
  UA: { name: "Ukraine", code: "UA", isziprequired: "T" },
  AE: { name: "United Arab Emirates", code: "AE", isziprequired: "F" },
  GB: {
    name: "United Kingdom",
    code: "GB",
    isziprequired: "T",
    states: [
      { name: "Aberdeenshire", code: "Aberdeenshire" },
      { name: "Angus", code: "Angus" },
      { name: "Argyll", code: "Argyll" },
      { name: "Avon", code: "Avon" },
      { name: "Ayrshire", code: "Ayrshire" },
      { name: "Banffshire", code: "Banffshire" },
      { name: "Bedfordshire", code: "Beds." },
      { name: "Berkshire", code: "Berks." },
      { name: "Berwickshire", code: "Berwickshire" },
      { name: "Buckinghamshire", code: "Bucks." },
      { name: "Caithness", code: "Caithness" },
      { name: "Cambridgeshire", code: "Cambs." },
      { name: "Cheshire", code: "Ches." },
      { name: "Clackmannanshire", code: "Clackmannanshire" },
      { name: "Cleveland", code: "Cleveland" },
      { name: "Clwyd", code: "Clwyd" },
      { name: "Cornwall", code: "Cornwall" },
      { name: "County Antrim", code: "Co Antrim" },
      { name: "County Armagh", code: "Co Armagh" },
      { name: "County Down", code: "Co Down" },
      { name: "County Durham", code: "Durham" },
      { name: "County Fermanagh", code: "Co Fermanagh" },
      { name: "County Londonderry", code: "Co Londonderry" },
      { name: "County Tyrone", code: "Co Tyrone" },
      { name: "Cumbria", code: "Cumbria" },
      { name: "Derbyshire", code: "Derbys." },
      { name: "Devon", code: "Devon" },
      { name: "Dorset", code: "Dorset" },
      { name: "Dumfriesshire", code: "Dumfriesshire" },
      { name: "Dunbartonshire", code: "Dunbartonshire" },
      { name: "Dyfed", code: "Dyfed" },
      { name: "East Lothian", code: "E Lothian" },
      { name: "East Sussex", code: "E Sussex" },
      { name: "Essex", code: "Essex" },
      { name: "Fife", code: "Fife" },
      { name: "Gloucestershire", code: "Gloucs." },
      { name: "Greater London", code: "London" },
      { name: "Gwent", code: "Gwent" },
      { name: "Gwynedd", code: "Gwynedd" },
      { name: "Hampshire", code: "Hants." },
      { name: "Herefordshire", code: "Hereford" },
      { name: "Hertfordshire", code: "Herts." },
      { name: "Inverness-shire", code: "Inverness-shire" },
      { name: "Isle of Arran", code: "Isle of Arran" },
      { name: "Isle of Barra", code: "Isle of Barra" },
      { name: "Isle of Benbecula", code: "Isle of Benbecula" },
      { name: "Isle of Bute", code: "Isle of Bute" },
      { name: "Isle of Canna", code: "Isle of Canna" },
      { name: "Isle of Coll", code: "Isle of Coll" },
      { name: "Isle of Colonsay", code: "Isle of Colonsay" },
      { name: "Isle of Cumbrae", code: "Isle of Cumbrae" },
      { name: "Isle of Eigg", code: "Isle of Eigg" },
      { name: "Isle of Gigha", code: "Isle of Gigha" },
      { name: "Isle of Harris", code: "Isle of Harris" },
      { name: "Isle of Iona", code: "Isle of Iona" },
      { name: "Isle of Islay", code: "Isle of Islay" },
      { name: "Isle of Jura", code: "Isle of Jura" },
      { name: "Isle of Lewis", code: "Isle of Lewis" },
      { name: "Isle of Mull", code: "Isle of Mull" },
      { name: "Isle of North Uist", code: "Isle of North Uist" },
      { name: "Isle of Rum", code: "Isle of Rum" },
      { name: "Isle of Scalpay", code: "Isle of Scalpay" },
      { name: "Isle of Skye", code: "Isle of Skye" },
      { name: "Isle of South Uist", code: "Isle of South Uist" },
      { name: "Isle of Tiree", code: "Isle of Tiree" },
      { name: "Isle of Wight", code: "Isle of Wight" },
      { name: "Kent", code: "Kent" },
      { name: "Kincardineshire", code: "Kincardineshire" },
      { name: "Kinross-shire", code: "Kinross-shire" },
      { name: "Kirkcudbrightshire", code: "Kirkcudbrightshire" },
      { name: "Lanarkshire", code: "Lanarkshire" },
      { name: "Lancashire", code: "Lancs." },
      { name: "Leicestershire", code: "Leics." },
      { name: "Lincolnshire", code: "Lincs." },
      { name: "Merseyside", code: "Merseyside" },
      { name: "Mid Glamorgan", code: "M Glam" },
      { name: "Mid Lothian", code: "Mid Lothian" },
      { name: "Middlesex", code: "Middx." },
      { name: "Morayshire", code: "Morayshire" },
      { name: "Nairnshire", code: "Nairnshire" },
      { name: "Norfolk", code: "Norfolk" },
      { name: "North Humberside", code: "N Humberside" },
      { name: "North Yorkshire", code: "N Yorkshire" },
      { name: "Northamptonshire", code: "Northants." },
      { name: "Northumberland", code: "Northumberland" },
      { name: "Nottinghamshire", code: "Notts." },
      { name: "Oxfordshire", code: "Oxon." },
      { name: "Peeblesshire", code: "Peeblesshire" },
      { name: "Perthshire", code: "Perthshire" },
      { name: "Powys", code: "Powys" },
      { name: "Renfrewshire", code: "Renfrewshire" },
      { name: "Ross-shire", code: "Ross-shire" },
      { name: "Roxburghshire", code: "Roxburghshire" },
      { name: "Selkirkshire", code: "Selkirkshire" },
      { name: "Shropshire", code: "Shrops" },
      { name: "Somerset", code: "Somt." },
      { name: "South Glamorgan", code: "S Glam" },
      { name: "South Humberside", code: "S Humberside" },
      { name: "South Yorkshire", code: "S Yorkshire" },
      { name: "Staffordshire", code: "Staffs." },
      { name: "Stirlingshire", code: "Stirlingshire" },
      { name: "Suffolk", code: "Suffolk" },
      { name: "Surrey", code: "Surrey" },
      { name: "Sutherland", code: "Sutherland" },
      { name: "Tyne and Wear", code: "Tyne & Wear" },
      { name: "Warwickshire", code: "Warks" },
      { name: "West Glamorgan", code: "W Glam" },
      { name: "West Lothian", code: "W Lothian" },
      { name: "West Midlands", code: "W Midlands" },
      { name: "West Sussex", code: "W Sussex" },
      { name: "West Yorkshire", code: "W Yorkshire" },
      { name: "Wigtownshire", code: "Wigtownshire" },
      { name: "Wiltshire", code: "Wilts" },
      { name: "Worcestershire", code: "Worcs" },
    ],
  },
  US: {
    name: "United States",
    code: "US",
    isziprequired: "T",
    states: [
      { name: "Alabama", code: "AL" },
      { name: "Alaska", code: "AK" },
      { name: "Arizona", code: "AZ" },
      { name: "Arkansas", code: "AR" },
      { name: "Armed Forces Americas", code: "AA" },
      { name: "Armed Forces Europe", code: "AE" },
      { name: "Armed Forces Pacific", code: "AP" },
      { name: "California", code: "CA" },
      { name: "Colorado", code: "CO" },
      { name: "Connecticut", code: "CT" },
      { name: "Delaware", code: "DE" },
      { name: "District of Columbia", code: "DC" },
      { name: "Florida", code: "FL" },
      { name: "Georgia", code: "GA" },
      { name: "Hawaii", code: "HI" },
      { name: "Idaho", code: "ID" },
      { name: "Illinois", code: "IL" },
      { name: "Indiana", code: "IN" },
      { name: "Iowa", code: "IA" },
      { name: "Kansas", code: "KS" },
      { name: "Kentucky", code: "KY" },
      { name: "Louisiana", code: "LA" },
      { name: "Maine", code: "ME" },
      { name: "Maryland", code: "MD" },
      { name: "Massachusetts", code: "MA" },
      { name: "Michigan", code: "MI" },
      { name: "Minnesota", code: "MN" },
      { name: "Mississippi", code: "MS" },
      { name: "Missouri", code: "MO" },
      { name: "Montana", code: "MT" },
      { name: "Nebraska", code: "NE" },
      { name: "Nevada", code: "NV" },
      { name: "New Hampshire", code: "NH" },
      { name: "New Jersey", code: "NJ" },
      { name: "New Mexico", code: "NM" },
      { name: "New York", code: "NY" },
      { name: "North Carolina", code: "NC" },
      { name: "North Dakota", code: "ND" },
      { name: "Ohio", code: "OH" },
      { name: "Oklahoma", code: "OK" },
      { name: "Oregon", code: "OR" },
      { name: "Pennsylvania", code: "PA" },
      { name: "Puerto Rico", code: "PR" },
      { name: "Rhode Island", code: "RI" },
      { name: "South Carolina", code: "SC" },
      { name: "South Dakota", code: "SD" },
      { name: "Tennessee", code: "TN" },
      { name: "Texas", code: "TX" },
      { name: "Utah", code: "UT" },
      { name: "Vermont", code: "VT" },
      { name: "Virginia", code: "VA" },
      { name: "Washington", code: "WA" },
      { name: "West Virginia", code: "WV" },
      { name: "Wisconsin", code: "WI" },
      { name: "Wyoming", code: "WY" },
    ],
  },
  UY: { name: "Uruguay", code: "UY", isziprequired: "T" },
  UZ: { name: "Uzbekistan", code: "UZ", isziprequired: "T" },
  VU: { name: "Vanuatu", code: "VU", isziprequired: "T" },
  VE: { name: "Venezuela", code: "VE", isziprequired: "T" },
  VN: { name: "Vietnam", code: "VN", isziprequired: "T" },
  VG: { name: "Virgin Islands (British)", code: "VG", isziprequired: "T" },
  VI: { name: "Virgin Islands (USA)", code: "VI", isziprequired: "T" },
  WF: { name: "Wallis and Futuna", code: "WF", isziprequired: "T" },
  EH: { name: "Western Sahara", code: "EH", isziprequired: "T" },
  YE: { name: "Yemen", code: "YE", isziprequired: "T" },
  ZM: { name: "Zambia", code: "ZM", isziprequired: "T" },
  ZW: { name: "Zimbabwe", code: "ZW", isziprequired: "T" },
};
// return countries;
